// <auto-generated />
namespace Learn.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class aspnetuser_add_modelbase_fields1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aspnetuser_add_modelbase_fields1));
        
        string IMigrationMetadata.Id
        {
            get { return "201804101741044_aspnetuser_add_modelbase_fields1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
