// <auto-generated />
namespace Learn.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class update_fmk_role : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_fmk_role));
        
        string IMigrationMetadata.Id
        {
            get { return "201804150924509_update_fmk_role"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
